### ISSUE TITLE
The "Plugins" button in the settings menu is missing

### ISSUE THREAD

**Issue by BladeSlame** [bylampa/bylampa.github.io#2]
Hello!
There is about 3 days when the "Plugins" button in the settings menu is missing. While configuring the plugin, it seems ok with "200" code, but there is no the check mark indicates a successful connection.
The same issue with Android, LG WebOS and Windows NT.
Best regards.

**Comment by BladeSlame** [comment]
It seems the trouble may be because of the #60 commit, while changing the URLs structure for short links via tinyurl. What do U think about this?

**Comment by BazZziliuS** [comment]
> It seems the trouble may be because of the #60 commit, while changing the URLs structure for short links via tinyurl. What do U think about this?

The answer from the author is here https://t.me/lampa_plugins_uncensored/2423
